project_id = "fwatgrgbwgtueunihbwv"

[functions.validate-image]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.log-error]
verify_jwt = false

[functions.create-admin-account]
verify_jwt = false
